name: win-latest

on:
  workflow_dispatch:
    inputs:
      authcode:
        description: "CRD Code"
        required: true
      pincode:
        description: "6 digit PIN"
        required: true

jobs:
  setup:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initializing Setup
        run: ./setup/win-latest/setup.sh
      - name: Starting Chrome Remote Desktop (CRD)
        run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
      - name: Keep Alive
        run: ./setup/win-latest/timeout.sh
